macro(CopyInpaintingDlls)
    # copy necessary dependency DLLs to destination folder
    if(MSVC)
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_core.1.dll"       "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_sequential.1.dll" "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_avx2.1.dll"       "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_def.1.dll"        "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_core.1.dll"     "${CMAKE_BINARY_DIR}/bin/Debug/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_thread.1.dll"   "${CMAKE_BINARY_DIR}/bin/Debug/")  
		add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_sequential.1.dll"   "${CMAKE_BINARY_DIR}/bin/Debug/")		

        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_core.1.dll"       "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_sequential.1.dll" "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_avx2.1.dll"       "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_def.1.dll"        "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_core.1.dll"     "${CMAKE_BINARY_DIR}/bin/Release/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_thread.1.dll"   "${CMAKE_BINARY_DIR}/bin/Release/")
		add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_sequential.1.dll"   "${CMAKE_BINARY_DIR}/bin/Release/")

        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
		add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_core.1.dll"       "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_sequential.1.dll" "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_avx2.1.dll"       "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${MKL_ROOT_DIR}/redist/intel64/mkl_def.1.dll"        "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_core.1.dll"     "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
        add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_thread.1.dll"   "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
		add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${DAAL_ROOT_DIR}/redist/intel64/onedal_sequential.1.dll"   "${CMAKE_BINARY_DIR}/bin/RelWithDebInfo/")
    endif(MSVC)
endmacro()